### ISSUE TITLE
stream not working

### ISSUE THREAD

**Issue by gwamperter** [iNaD/download-station-zdfmediathek#8] opened 2016-02-18 21:48 UTC
Hi,
following stream is not working.

http://www.tivi.de/mediathek/pur-893542/ich-brauch-neue-eltern-2657754/

It would be great if you could help.

regards
gwamperter

**Comment by iNaD** [comment] 2017-09-22 18:21
duplicate of #10

**Closed by iNaD** 2017-09-22 18:21 UTC
Labels: duplicate, enhancement
